import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def create_report():
    pdf_filename = "enterprise_ai_knowledge_hub_report.pdf"
    
    # 0.5 inch margins
    doc = SimpleDocTemplate(
        pdf_filename, 
        pagesize=letter,
        rightMargin=36, 
        leftMargin=36, 
        topMargin=36, 
        bottomMargin=36
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#0f172a'),
        alignment=1, # Center
        spaceAfter=10
    )
    
    subtitle_style = ParagraphStyle(
        'SubtitleStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#475569'),
        alignment=1, # Center
        spaceAfter=20
    )
    
    h1_style = ParagraphStyle(
        'H1Style',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#1e293b'),
        spaceBefore=12,
        spaceAfter=6
    )
    
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['BodyText'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor('#334155'),
        spaceAfter=8
    )
    
    code_style = ParagraphStyle(
        'CodeStyle',
        parent=styles['Code'],
        fontName='Courier',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#0f172a'),
        backColor=colors.HexColor('#f8fafc'),
        borderColor=colors.HexColor('#e2e8f0'),
        borderWidth=0.5,
        borderPadding=6,
        spaceAfter=8
    )

    story = []
    
    # --- Title Section ---
    story.append(Paragraph("Major Project Report: Enterprise AI Knowledge Hub", title_style))
    story.append(Paragraph("Retrieval-Augmented Generation (RAG) System using LangChain & Gemini", subtitle_style))
    story.append(Spacer(1, 10))
    
    # --- Section 1: Executive Summary ---
    story.append(Paragraph("1. Executive Summary", h1_style))
    story.append(Paragraph(
        "The Enterprise AI Knowledge Hub is an intelligent document assistant designed to help organizations "
        "search and extract insights from their data. Utilizing a Retrieval-Augmented Generation (RAG) "
        "architecture, the system parses multi-format documents (PDF, DOCX, TXT, MD, HTML), indexes their "
        "contents into a high-performance local vector database (ChromaDB), and generates context-aware "
        "responses using the Google Gemini model. All answers are accompanied by verifiable source page "
        "citations to ensure truthfulness and eliminate LLM hallucinations.",
        body_style
    ))
    
    # --- Section 2: Key Features ---
    story.append(Paragraph("2. Key System Features", h1_style))
    story.append(Paragraph(
        "• <b>Multi-Format Ingestion:</b> Supports Word documents (.docx), PDFs (.pdf), plain text (.txt), Markdown (.md), and HTML files.<br/>"
        "• <b>Persistent ChromaDB Store:</b> Local database vector search using semantic embeddings generated by <i>models/gemini-embedding-001</i>.<br/>"
        "• <b>Conversational Retrieval:</b> Remembers previous questions in the session to handle follow-up queries naturally.<br/>"
        "• <b>Source Citation Expansion:</b> Shows the document name, page number, and text snippet for every generated response.<br/>"
        "• <b>Dynamic Document Manager:</b> Allows users to upload and delete documents dynamically on the sidebar interface.",
        body_style
    ))
    
    # --- Section 3: System Architecture ---
    story.append(Paragraph("3. Technical Architecture", h1_style))
    story.append(Paragraph(
        "The system pipeline consists of the following components:",
        body_style
    ))
    story.append(Paragraph(
        "1. <b>Document Loader:</b> Routes documents by file extension to appropriate LangChain parsers.<br/>"
        "2. <b>Text Splitter:</b> Chunks data using <i>RecursiveCharacterTextSplitter</i> (size: 1000, overlap: 200).<br/>"
        "3. <b>Vector Indexing:</b> Saves document embeddings in a persistent directory `./chroma_db`.<br/>"
        "4. <b>Conversational Chain:</b> Uses `gemini-3.5-flash` to synthesize answers using chat history and retrieved context.",
        code_style
    ))
    
    # --- Section 4: Application Screenshot ---
    story.append(PageBreak())
    story.append(Paragraph("4. User Interface Dashboard", h1_style))
    story.append(Paragraph(
        "The web application features a sleek, premium dark-mode dashboard created with Streamlit:",
        body_style
    ))
    
    if os.path.exists("app_screenshot.png"):
        story.append(Image("app_screenshot.png", width=480, height=270))
        story.append(Paragraph("<i>Figure 4.1: Deployed Streamlit Dashboard Interface</i>", subtitle_style))
        story.append(Spacer(1, 10))

    # --- Section 5: Setup & Execution Instructions ---
    story.append(Paragraph("5. Setup and Execution Instructions", h1_style))
    story.append(Paragraph(
        "To run the application locally, use the following commands:",
        body_style
    ))
    story.append(Paragraph(
        "git clone https://github.com/Amalbinu123/Enterprise_AI_Knowledge_Hub.git<br/>"
        "cd Enterprise_AI_Knowledge_Hub<br/>"
        "pip install -r requirements.txt<br/>"
        "streamlit run app.py",
        code_style
    ))
    
    story.append(Paragraph(
        "<b>Evaluation Note:</b> The project can be run using the live URL: "
        "<u>https://enterpriseaiknowledgeapp-fef3tkgx4qpguycyyhz2e8.streamlit.app/</u>. "
        "Evaluators can paste their own Gemini API key directly into the sidebar to test it instantly.",
        body_style
    ))

    # Build PDF
    doc.build(story)
    print("Major Project PDF Report generated successfully!")

if __name__ == "__main__":
    create_report()
